### ISSUE TITLE
No exchange error when sending to new group

### ISSUE THREAD

**Issue by whs** [proofit404/asgi_rabbitmq#11]
When sending a Group message to a group that have no subscribers, `ChannelClosed: (404, "NOT_FOUND - no exchange 'groupname' in vhost '/'")` will trigger.

It seems that unlike `send`, `send_group` have no `queue_declare` call before message sending.

**Comment by proofit404** [comment]
Hi,

What version do you use?

Master has no problem with not declared groups. Here is test case to prove that https://github.com/proofit404/asgi_rabbitmq/blob/master/tests/test_unit.py#L66-L70

Can you provide more detailed description of the issue?

**Comment by whs** [comment]
I was running 0.5.2, RabbitMQ 3.6.10 w/HiPE+Management from Docker Hub. [Here is the exception from Sentry](https://sentry.io/share/issue/3133383132322e333233333330393335/).

I'll try master and report later.

**Comment by whs** [comment]
I tested from master and still experience the same issue.

I made a minimal project to reproduce: https://github.com/whs/asgi_rabbitmq_reproc . The view code is entirely in root urlconf. When I run `python manage.py runserver` (alongside a RabbitMQ Docker container) and go to localhost:8000 the console will log `pika.exceptions.ChannelClosed: (404, "NOT_FOUND - no exchange 'demo0.40076687179733983' in vhost '/'")`

**Comment by proofit404** [comment]
This fix is available in v0.5.3. You can install it from PyPI.

**Comment by whs** [comment]
It works! Thanks :)
