### ISSUE TITLE
Reconnection scheme [pika.ConnectionClosed]

### ISSUE THREAD

**Issue by adriancarayol** [proofit404/asgi_rabbitmq#16]
In: https://github.com/proofit404/asgi_rabbitmq/blob/6c9cddff850bccbc8781bee9c82788b3e8be3185/asgi_rabbitmq/core.py#L691

you could try reconnecting with pika again (try 2 or 3 times)? would be very useful for long connections where pika may fall.

**Comment by proofit404** [comment]
Hi,

This change should be ASGI compliant. Can you explain what situation you have in the production? So I can decide if this feature is necessary or not.

Thanks, Artem.

**Comment by adriancarayol** [comment]
Hi,

when I establish heartbeat, for example to 60, spent a long time pika closes the connection and Django (with daphne and a worker) stops working.

**Comment by proofit404** [comment]
Maybe you should tune heartbeat setting to an appropriate value for your network? Or disable it at all and use TCP heartbeat instead?

**Comment by adriancarayol** [comment]
Removing "heartbeat" param from URL seems to no longer close the connection...

**Comment by proofit404** [comment]
Sorry I didn't get you. Please explain your problem with reproduction steps.

**Comment by adriancarayol** [comment]
Yes, if url is amqp://guest:guest@rabbitmq:5672/%2F?heartbeat=60, for example, pika connection will it closed, and raised pika.ConnectionClose exception when the server is running for a long time, and the server crashes.

Error when retrieving messages in the rabbitmq log.

If heartbeat parameter is removed, error disappear, (for now).

**Comment by proofit404** [comment]
That means that your RabbitMQ server doesn't send heartbeat frames over your connection.  The library is properly failing according to the given settings. Please fix your RabbitMQ installation. Also if heartbeat loss is an unexpected situation you need to configure your systemd or supervisord to restart channels infrastructure.
