### ISSUE TITLE
asgi_ipc v1.5.0 phantom requirement

### ISSUE THREAD

**Issue by caronc** [proofit404/asgi_rabbitmq#18]
Just a quick question on line 6 of [this](https://github.com/proofit404/asgi_rabbitmq/commit/8705c7bc14be6e25ea3f2581f8b50fdbcb61dd70) commit you made back in June.
```
# Save you from clicking the link; but you added this to your asgi_rabbitmq dependencies:
# The change was from asgi_ipc v1.3.1
git+https://github.com/django/asgi_ipc.git#egg=asgi_ipc-1.5.0
```
asgi_ipc v1.4.2 was just released 9 days ago, yet this commit you made here was way back in June. Is the current version of asgi_ipc safe to use?

## The Back Story
Currently I'm using asgi_rabbitmq (v1.5.1) but websockets completely stops working when upgrade (asgi_rabbitmq) to v1.5.4.

I'm still in the process of debugging this myself as i don't think the issue is on your end.  I noticed that between your commits of v1.5.1 and v1.5.4 Pika v0.11 is required in addition to the phantom asgi_ipc version :wink:.

So far I'm using:
* Django v1.10.7: CentOS/RedHat 7.x ships with PostgreSQL v9.2 and v1.11 [claims to have dropped support for it](https://docs.djangoproject.com/en/1.11/releases/1.11/#dropped-support-for-postgresql-9-2-and-postgis-2-0).  For this reason i haven't made the jump forward yet since i haven't taken on the ripple effect.
* Django Channels v1.1.8
* Daphne v1.3.0
* asgi_ipc v1.4.2: I'm confused with the v1.5.0 reference (hence this ticket)
* pika v0.10.0: (will update this)
* Python v2.7.5: I know, I know... it's old; but it's the version shipped with CentOS/RedHat 7.x. Unlike other distro's it's got all of their mainstream fixes (so it's actually more of a v2.7.5+++ since it includes all bugfixes and CVE's to present time).

Using the above asgi_rabbitmq v1.5.1 works great; but I'm interested in the *deadletter* cleanup's you've added since (RabbitMQ) queues build quickly and remain stale as people come and go.

**Comment by proofit404** [comment]
Thanks! Fixed in master.

Please report an issue, if you find something not working after upgrade to the recent version.

Have a good day.
