### ISSUE TITLE
Resource cleanup

### ISSUE THREAD

**Issue by proofit404** [proofit404/asgi_rabbitmq#3]
[Resource cleanup](http://asgi-rabbitmq.readthedocs.io/en/latest/development/protocol.html#resource-cleanup) should be improved.  At this point all possible solutions will be incompatible with ASGI spec.  I try to describe proposed solution in terms of RabbitMQ protocol convention.

### Exchange cleanup

All exchanges can be declared with `auto-delete` flag.  When we can cleanup all intermediate queues properly exchanges will also be removed.

**Spec changes**: Not necessary.

### Process local channels

Corresponding queue can be declared with `exclusive` flag.  This queue will be remove when process created this queue closes connection.  This queue can't be declared in the passive mode, so we can't check numbers of messages in it.  Also we should create this queue from process which gonna read from it.

**Spec changes**: Create process local channels with `new_channel` method again.  Remove capacity from process local channels.

### Single reader channels

Corresponding queue can be declared with `auto-delete` flag.  After that we start consumer with `no-local` flag.  This will prevent it from reading messages sent from same connection.  Queue will we cleanup when this consumer goes away.  Obviously that will happens when connection was closed.

**Spec changes**: Limit single reader channels receive and send usage.  Receive can't be used from process created channel with `new_channel`.  Send can be used *only* from process which creates this queue with `new_channel`.

So let brain storm here and decide if this changes are appropriate to spec.

cc @andrewgodwin @apollo13

**Comment by andrewgodwin** [comment]
Process-local channel exclusivity: Do we need new_channel? Can we not just create the queue in this way when we get a `receive()` call on it and it contains the `!` character?

Process-local channel capacity: Hmm, capacity is important for buffering large responses, otherwise it might try and push a 100MB file down into the message queue all at once. Is there no other solution to this?

Single-reader: I think we could say that you can only send to it from the place that called new_channel without too much hassle. and not allow receiving, and maybe rename it "Single source channels" to enforce this, which also reflects the difference in sharding we need to handle in the Redis backend.

**Comment by proofit404** [comment]
### Single reader channels

Looks like we agree on this?

### Process local channels

Probably we can do the same thing with long running consumer and `auto-delete` flag. This consumer will receive messages immediately and store in the connection internal cache. Until some one call receive from this channel. Also experimental twisted support is done the same way in the separate branch.

This way we can use declare operation with passive flag. So worker will be able to check queue length.

Starting this internal consumer on the first call to the receive is possible. I need to check it.

**Comment by apollo13** [comment]
I have been reading https://asgi-rabbitmq.readthedocs.io/en/latest/development/protocol.html and thought about what I did when I tried to implementing a rabbit mq backend.

I especially tried to avoid:
>  We declare queue before each message sending. When we receive Declare.Ok response, it contains number of messages in the queue.

How much overhead is that in general? If that turns out to be much, we'd probably have to rethink the whole approach on rabbitmq

**Comment by proofit404** [comment]
Hi @apollo13 Thanks for your feedback.

I've developed AMQP testing tool for pika library. Each CI test runs with this statistic module enabled.

As you can see additional Queue.Declare call add `0.0006` seconds overhead to each layer send call. I think it is appropriate. [Proof](https://travis-ci.org/proofit404/asgi_rabbitmq/jobs/222382704#L752).

But I totally agree that approach described in the protocol is far from convenient RabbitMQ usage. ASGI compatibility was my main goal.

**Comment by proofit404** [comment]
I've tried to implement single reader channels in the suggested way. Turns out RabbitMQ doesn't support `no-local` consumer flag. I need to find another way to cleanup those queues.

Also declaring group exchange with `auto-delete` flag make no sense. E2E bindings doesn't prevent it from from cleanup. And this isn't desired behavior.

**Comment by proofit404** [comment]
@andrewgodwin Can you clarify single-reader channels semantic for me?

1. How many messages single-reader channel must hold?
2. Should it allows to be read from only one (unknown) process?
3. What is intended way to use it in Daphne + Channels pair?

Depends on this we can cleanup this queue in different ways:
- send `Queue.Delete` with `if-empty` after each `Basic.Get`. Each `receive` in the blocking mode can cleanup queue.
- combine `Queue.Declare` `auto-delete` and Exclusive consumer. Queue will be removed after worker teardown.

Also I think it is good idea to set Queue TTL equals message expiration multiplied by some number (x2 probably). This way we can remove unused queues eventually if **everything** goes wrong.

**Comment by andrewgodwin** [comment]
Sorry I let this one languish in my inbox for so long, I somehow overlooked it.

1. It should hold whatever the capacity setting is has is set to.
2. Currently the spec says it can be read from multiple places but there's only good ordering guarantees if it's read from a single place; I would be fine saying it must only be read from one unknown location.
3. It's intended for HTTP bodies, where Daphne makes a single-reader channel and passes the name in the Request message, and then the Django side consumes that channel to read chunks of the body. as Daphne feeds them in.

**Comment by proofit404** [comment]
I think we can try to call `Queue.Delete` method with `if-empty` argument on each receive and from dead letter consumer.

I even think this is the most simple solution for all kind of cannels. Hopefully I'll try it soon.

**Comment by proofit404** [comment]
@ollamh As I understand you're using asgi-rabbitmq in your product. Please note that this issue may affect your production environment under real load. Please setup resource monitoring for RabbitMQ nodes.

If this issue affects you already, I can develop ad-hoc cleaner as temporary solution.

**Comment by ollamh** [comment]
@proofit404 Thanks for caring about that! We're not yet in production, but I believe we'll be there in a month or so.. And, yes, I can see lots of queues/exchanges left after client disconnecting. If you need any help on that, I definitely will do my best to help to ship this feature asap.

**Comment by proofit404** [comment]
Constant Queue.Delete calls are not working as well. They create conditions when send creates a queue, concurrent receive deletes queue and running send fails to push message into this queue.

So Queue TTL is the only working model. I set it to message expiry X2, so clean up will robust with reasonably low message expiry values.

I need update protocol docs, review tests one more time and I will be able to release it.

**Comment by ollamh** [comment]
@proofit404 Thank you very much, this is definitely what I need!

**Comment by proofit404** [comment]
This issue is resolved in master. I'll ship new release soon.

**Comment by proofit404** [comment]
`asgi_rabbitmq` `v0.5` was released.
