### ISSUE TITLE
SSL support?

### ISSUE THREAD

**Issue by knipknap** [proofit404/asgi_rabbitmq#4]
Can I use the backend to connect to RabbitMQ via SSL? I am not sure if symmetric_encryption_keys is what I need.

**Comment by proofit404** [comment]
Closed via 4cb9d85.

**Comment by proofit404** [comment]
http://asgi-rabbitmq.readthedocs.io/en/latest/usage.html#ssl-connection

Thanks for feedback!

**Comment by knipknap** [comment]
Awesome :-) Thanks for the fast response!
