### ISSUE TITLE
Queue Control

### ISSUE THREAD

**Issue by caronc** [proofit404/asgi_rabbitmq#7]
One of the greatest features of RabbitMQ is the ability to sort different tasks in different queues (to which can be read/processed on different servers)... Hence you could have all your _image workers_ only watch the **image** queue and maybe some _other worker_ only read from a **cache** queue, etc.

But with this plugin, it seems to generate A LOT of queues.  It makes it non-trivial to have the webserver not exclusively watch a queue to it's own but is instead required to run without filters in place... For example; here is my queue list after just a few minutes with just 1 client (disconnecting and reconnecting the websocket a few times). The list is huge (when prior it was just 3 queues, - celery, web, and cache).
```bash
# List Queue Command:
sudo rabbitmqctl list_queues -p myvhost
Listing queues ...
expire.bind.p-1.daphne.response.fqyXMkPNez!hQiCxdHiQx	1
websocket.connect	0
expire.bind.c-718705ea-372a-47c3-846d-06fba79b8cc9.daphne.response.nthWTiCZzT!KIOiIZIaNh	1
expire.bind.c-718705ea-372a-47c3-846d-06fba79b8cc9.daphne.response.fqyXMkPNez!FpkBDvADWm	1
expire.bind.c-718705ea-372a-47c3-846d-06fba79b8cc9.daphne.response.GqzRsAcEza!dBDmOxOVWY	1
daphne.response.fqyXMkPNez!FpkBDvADWm	0
daphne.response.GqzRsAcEza!dBDmOxOVWY	0
celery	0
expire.bind.p-1.daphne.response.GqzRsAcEza!FgVpfWfxbu	1
expire.bind.c-718705ea-372a-47c3-846d-06fba79b8cc9.daphne.response.fqyXMkPNez!hQiCxdHiQx	1
expire.bind.p-1.daphne.response.IkSouWPyWh!NfczWgeizR	1
daphne.response.cDYwxqxlQS!EHUcRmVskU	0
daphne.response.fqyXMkPNez!fMruwjfKcL	0
expire.bind.c-718705ea-372a-47c3-846d-06fba79b8cc9.daphne.response.fqyXMkPNez!fMruwjfKcL	1
expire.bind.p-1.daphne.response.fqyXMkPNez!fMruwjfKcL	1
expire.bind.p-1.daphne.response.IkSouWPyWh!bVXSbsrZBR	1
expire.bind.p-1.daphne.response.fqyXMkPNez!uKusKVDDoj	1
daphne.response.fqyXMkPNez!uKusKVDDoj	0
expire.bind.c-718705ea-372a-47c3-846d-06fba79b8cc9.daphne.response.cDYwxqxlQS!kEcbAWNefs	1
expire.bind.p-1.daphne.response.cDYwxqxlQS!kEcbAWNefs	1
websocket.receive	0
expire.bind.c-718705ea-372a-47c3-846d-06fba79b8cc9.daphne.response.IkSouWPyWh!NfczWgeizR	1
daphne.response.cDYwxqxlQS!wjLHrTSAhn	0
celery@upstairs.lead2gold.local.celery.pidbox	0
expire.bind.p-1.daphne.response.cDYwxqxlQS!EHUcRmVskU	1
web	0
daphne.response.cDYwxqxlQS!kEcbAWNefs	0
expire.bind.c-718705ea-372a-47c3-846d-06fba79b8cc9.daphne.response.GqzRsAcEza!FgVpfWfxbu	1
celeryev.2772ee04-1646-44aa-81a1-df39b809c858	0
http.request	0
expire.bind.c-718705ea-372a-47c3-846d-06fba79b8cc9.daphne.response.nthWTiCZzT!yQunJrZRws	1
daphne.response.nthWTiCZzT!KIOiIZIaNh	0
expire.bind.c-718705ea-372a-47c3-846d-06fba79b8cc9.daphne.response.fqyXMkPNez!uKusKVDDoj	1
expire.bind.p-1.daphne.response.fqyXMkPNez!FpkBDvADWm	1
expire.bind.c-718705ea-372a-47c3-846d-06fba79b8cc9.daphne.response.cDYwxqxlQS!EHUcRmVskU	1
expire.bind.p-1.daphne.response.cDYwxqxlQS!wjLHrTSAhn	1
daphne.response.fqyXMkPNez!hQiCxdHiQx	0
daphne.response.nthWTiCZzT!yQunJrZRws	0
expire.bind.p-1.daphne.response.GqzRsAcEza!dBDmOxOVWY	1
expire.bind.p-1.daphne.response.nthWTiCZzT!yQunJrZRws	1
websocket.disconnect	0
daphne.response.GqzRsAcEza!FgVpfWfxbu	0
expire.bind.c-718705ea-372a-47c3-846d-06fba79b8cc9.daphne.response.IkSouWPyWh!bVXSbsrZBR	1
dead-letters	0
expire.bind.p-1.daphne.response.nthWTiCZzT!KIOiIZIaNh	1
cache	0
daphne.response.cDYwxqxlQS!	0
expire.bind.c-718705ea-372a-47c3-846d-06fba79b8cc9.daphne.response.cDYwxqxlQS!wjLHrTSAhn	1
```
There are a lot of **expire.bind.***, **daphne.response.*** and in some cases **<hex>.daphne.***.

I imagine you use the queue names in some way to track to the web requests? Would it be feasible to just create 1 queue and work within it? Perhaps call it daphne (or allow us to define it) and place content in there? The message itself could contain the information you're otherwise putting in the queue name in addition to the payload that is already there?

At the end of the day, I suppose i could just create a dedicated vhost exclusively for this asgi interface to use separating it completely from the rest of the website and their queues)? Maybe this is the route you'd recommend?

I'm just curious on your thoughts (or maybe just my misinterpretation on the matter) :smile: .

**Comment by proofit404** [comment]
Hi,

Thanks for your interest. `asgi_rabbitmq` has comprehensive documentation on its own. Here you can find a purpose for each created queue: [protocol](http://asgi-rabbitmq.readthedocs.io/en/latest/development/protocol.html). asgi_rabbitmq is a generic realization of ASGI protocol, so we can't rely on some specific use cases like WebSocket or HTTP connections. Of course, this means we doesn't use RabbitMQ in the most optimal way, but ASGI compatibility was the main goal. 

Separate virtual host for channels will be the right choice. I'll add this as a recommendation for the production environment in the docs.

**Comment by proofit404** [comment]
If you provide complete example I can double check that everything works as expected.

**Comment by caronc** [comment]
> Thanks for your interest. asgi_rabbitmq has comprehensive documentation on its own.
I love it; you and @andrewgodwin are doing a fantastic job with channels and it's documentation. My hat is off to you both.

I read the information you provided in your last post about how you're basically associating the web channels with queues and maintaining them that way.  So the queue's make sense; it would be interesting to see how it scales though.  We're talking about a queue per user plus a queue per group we create.  Have you had any feedback on how many active queues you've reached using your plugin? Production type numbers?

[Tim Watson (RabbitMQ developer) states in this post here](http://rabbitmq.1065348.n5.nabble.com/Max-messages-allowed-in-a-queue-in-RabbitMQ-td26063.html):
>  Each queue is managed by its own process and each connection can result in several more, so if you're planning on having a very large number of active queues in a single node (?) and using them all at the same time, then you may need to tweak the emulator arguments rabbit passes the VM by setting +P <new limit> to a higher limit. 

> You're also likely to use up many Gb just with the overhead for each queue / connection pretty fast, so you're going to need a pretty meaty server to handle millions of both. Tens of thousands should be no problem at all, providing they fit into RAM. 

I could see asgi_rabbitmq taking in multiple rabbitmq servers and providing some kind of round-robin load balancing based on the number provided (maybe base it on the first character of the hex in the uuid4).  That would allow easy growth of queues beyond the 'tens of thousands' reference if needed? 

```python
# something like...
# Channels
CHANNEL_LAYERS = {
    "default": {
        'BACKEND': 'asgi_rabbitmq.RabbitmqChannelLayer',
        'CONFIG': {
            'url': [ BROKER_URL_01, BROKER_URL_02, BROKER_URL_03 ]
        },
        "ROUTING": "example.routing.channel_routing",
    },
}
```
Your thoughts?

> If you provide complete example I can double check that everything works as expected.

Well for my development environment, i'm using the following commands (scripted) to just start it up:
```bash
# simply fire up a worker with a pid i can monitor since i'm launching
# it in the background (DJANGO_SETTINGS_MODULE already
# exported in the background so it references my dev settings)
# in my dev environment the -Q includes all 3 of my queues i use often
# however in production the front end webserver launches it's
# instances with just -Q celery,web while my backend cache servers
# launch with -Q cache
celery --app=example  worker --beat \
      -l debug \
      --concurrency=1 \
      -Q celery,web,cache \
      --pidfile $(pwd)/worker.pid &

# the command we always use :)
# This blocks until ctrl-c is pressed which makes the next
# line that follows only get executed at this time too
django_manage runserver      $MYIPADDR:$MYPORT
kill $(<$(pwd)/worker.pid))
```

As per settings, i'm currently putting this all in one vhost; it was late last night when i saw you're reply, so i'll separate this into it's own vhost when i get home to see how it works.  but currently settings/base.py (looks like this):
```python

# Application definition
INSTALLED_APPS = [
    ...

    # Django Channels
    'channels',

    # Celery
    'djcelery',

    # My Managed App
    'example',
]

# Use SSL (can't make this work yet - not your problem though) :)
BROKER_USE_SSL = False

# some other RabbitMQ/Celery settings here that aren't really applicable to
# your question are here ...

# RabbitMQ Broker provides AMQP Services
BROKER_URL = 'amqp://{user}:{password}@{hostname}:{port}/{vhost}'.format(
    user=os.environ.get('RABBITMQ_USER', 'example'),
    password=os.environ.get('RABBITMQ_PASS', 'example'),
    hostname=os.environ.get('RABBITMQ_NODE_IP_ADDRESS', 'server01.local'),
    port=os.environ.get('RABBITMQ_NODE_PORT', '5671' \
                        if BROKER_USE_SSL else '5672'),
    vhost=os.environ.get('RABBITMQ_VHOST', 'example'),
)

# Channels
CHANNEL_LAYERS = {
    "default": {
        'BACKEND': 'asgi_rabbitmq.RabbitmqChannelLayer',
        'CONFIG': {
            'url': BROKER_URL,
        },
        "ROUTING": "example.routing.channel_routing",
    },
}
```

Based on our convo, i'll probably do this next:
```python

# RabbitMQ Broker provides AMQP Services
BROKER_URL = 'amqp://{user}:{password}@{hostname}:{port}/{vhost}'.format(
    user=os.environ.get('RABBITMQ_USER', 'example'),
    password=os.environ.get('RABBITMQ_PASS', 'example'),
    hostname=os.environ.get('RABBITMQ_NODE_IP_ADDRESS', 'server01.local'),
    port=os.environ.get('RABBITMQ_NODE_PORT', '5671' \
                        if BROKER_USE_SSL else '5672'),
    vhost=os.environ.get('RABBITMQ_VHOST', 'example.base'),
)

# RabbitMQ Broker provides AMQP Services
CHANNELS_BROKER_URL = 'amqp://{user}:{password}@{hostname}:{port}/{vhost}'.format(
    user=os.environ.get('RABBITMQ_USER', 'example'),
    password=os.environ.get('RABBITMQ_PASS', 'example'),
    hostname=os.environ.get('RABBITMQ_NODE_IP_ADDRESS', 'server01.local'),
    port=os.environ.get('RABBITMQ_NODE_PORT', '5671' \
                        if BROKER_USE_SSL else '5672'),
    vhost=os.environ.get('RABBITMQ_VHOST', 'example.channels'),
)

# Channels
CHANNEL_LAYERS = {
    "default": {
        'BACKEND': 'asgi_rabbitmq.RabbitmqChannelLayer',
        'CONFIG': {
            'url': CHANNEL_BROKER_URL,
        },
        "ROUTING": "example.routing.channel_routing",
    },
}
```

Sorry for such a winded response; I'm not sure if i answered your question on the complete example or not.  Keep up the awesome work!
